import Head from 'next/head'
import Navbar from '../components/Navbar'
import Footer from '../components/Footer'
import HomePage from './homePage'
import Services from './Services'
import Works from './Work'
import Clients from './Clients'
import Contact from './Contact'

export default function Home() {
  return (
    <div>
      <Head>
        <title>My Porfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <HomePage/>
      <Services/>
      <Works/>
      <Clients/>
      <Contact/>
      <Footer/>
    </div>
  )
}
